<?php

declare(strict_types=1);

namespace Webidea24\MagentoComposerPatches\Command;

use Composer\Command\BaseCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Webidea24\MagentoComposerPatches\Configuration\PatchUrlSynchronizer;

final class RemovePatchesCommand extends BaseCommand
{
    protected function configure(): void
    {
        $this->setName('magento-patches:remove')
            ->setDescription('Remove patch URLs generated by this package.');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $removedPatches = (new PatchUrlSynchronizer($this->requireComposer()))->remove();
        $this->getIO()
            ->write(sprintf(
                '<info>Removed %d remote package patch%s.</info>',
                $removedPatches,
                $removedPatches === 1 ? '' : 'es',
            ));

        return 0;
    }
}
